package millenniumfinance.backend.classes.binance.enumerations;

public enum FilterType {
  EXCHANGE_MAX_NUM_ALGO_ORDERS,
  EXCHANGE_MAX_NUM_ORDERS,
  ICEBERG_PARTS,
  LOT_SIZE,
  MARKET_LOT_SIZE,
  MAX_NUM_ALGO_ORDERS,
  MAX_NUM_ICEBERG_ORDERS,
  MAX_NUM_ORDERS,
  MAX_POSITION,
  MIN_NOTIONAL,
  PERCENT_PRICE,
  PRICE_FILTER
}
